version: "3.9"
services:
  agent:
    build: .
    ports: ["8080:8080"]
    environment:
      # set this to point at your existing RAG API when you want to show migration
      - RAG_RETRIEVE_URL=
      - LLM=mock     # or: ollama / openai
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.1
      - OPENAI_API_KEY=
      - OPENAI_MODEL=gpt-4o-mini